#!/user/bin/evn python3


dect = {"f": "а", "l": "д", "q": "й", "w": "ц", "e": "у", "r": "к", "t": "е", "y": "н", "u": "г", "i": "ш", "o": "щ", "p": "з",  "a": "ф", "s": "ы", "d": "в", "g": "п", "h": "р", "k": "л", ";": "ж", "'": "э", "z": "я", "x": "ч", "j": "о", "c": "с", "v": "м", "b": "и", "n": "т", "m": "ь", "[": "х", "]": "ъ", ",": "б", ".": "ю"}
lst = input("Enter the word: ")
lst = list(lst)

for a in dect:
 for b in lst:
    if b == a:
           print(dect.get(b))
